[33mbee8301[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmain[m[33m, [m[1;31morigin/main[m[33m)[m 모든 .md 파일의 날짜를 2025년 09월 19일로 통일
[33md535213[m Enterprise Edition UI 완성 - 배치 분석, 입력 검증, 신뢰도 평가 UI 추가
[33m20df04a[m 🚀 v2.16.0-enterprise: ChatGPT/Claude 수준의 엔터프라이즈급 시스템으로 완전 업그레이드
[33m9c00504[m Upgrade to Enterprise Edition - Transform app.py into ChatGPT/Claude level system - Add AdvancedValidationSystem with multi-level validation - Add AdvancedConfidenceSystem with multi-source confidence scoring - Implement comprehensive error handling and recovery mechanisms - Add async processing and caching capabilities - Add enterprise-grade API endpoints (health, metrics, batch, export) - Add security enhancements and input sanitization - Add performance monitoring and logging - Update requirements.txt with enterprise dependencies - Add comprehensive demo script for testing all features
[33m7dc2245[m Fix Truth Score Consistency Issues - Add AIConsistentDetector for deterministic scoring - Implement result caching system to ensure identical results - Add consistency test mode to verify score stability - Add comprehensive UI for consistency analysis and testing - Ensure same statement always returns same truth percentage - Add detailed statistics and monitoring for score variations
[33m16c357c[m Upgrade AI Web Research System with Real-time Progress Display - Add AIEnhancedResearcher with real-time search progress tracking - Add Korean language progress descriptions and status updates - Integrate enhanced research mode into Flask app and web interface - Add timeline visualization for search process - Add detailed source information with search engine and keyword tracking - Add comprehensive demo script for testing enhanced features
[33meb02674[m Add AI Web Research System - Add web search and fact verification capabilities - Integrate with Flask app and web interface - Add research and verification analysis modes - Create comprehensive question-answering system - Add demo script for testing
[33m05076af[m Fix analysis mode selection UI - Remove default active state from integrated analysis button - Add user-friendly mode selection feedback - Add visual feedback when mode is selected - Add warning when no mode is selected - Improve button styling for better UX
[33mfb90fd7[m Integrate AI Self-Truth Detection Systems with Flask App - Add AI self-truth detection systems to app.py - Add new API endpoints for AI self-analysis - Update index.html with AI self-analysis modes - Add comprehensive AI self-analysis result display - Support real-time monitoring and meta-cognitive analysis
[33m9ee4d01[m Complete AI Truth Detection System - Add comprehensive AI self-truth detection systems - Add real-time monitoring and auto-correction - Add meta-cognitive truth analysis - Add demo and testing scripts - Complete documentation and README
